(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Field nombre does not belong to the table"
p3
sS'layer'
p4
S'/opt/python/web2py-files/web2py/applications/proyect/controllers/especialista.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# this file is released under public domain and you can use without limitations\n\n@auth.requires_membership("Especialista")\ndef lista_diagnostico():\n    response.flash = T("Listado de Diagn\xc3\xb3stico")\n    response.title = T("Listado de Diagn\xc3\xb3stico") + response.title\n    return dict()\n\n@auth.requires_membership("Especialista")\ndef nuevo_diagnostico():\n    response.flash = T("Nuevo Diagn\xc3\xb3stico")\n    response.title = T("Nuevo Diagn\xc3\xb3stico") + response.title\n\n    form = SQLFORM(db.diagnostico_inicial)\n\n    if form.validate():\n        form.vars.id = db.auth_user.insert(**dict(form.vars))\n\n        response.flash = T(\'Nuevo cuestionario Diagn\xc3\xb3stico Inicial insertado\')\n\n    elif form.errors:\n        response.flash = T(\'El formulario tiene errores\')\n    else:\n        response.flash = T(\'Por favor complete el formulario\')\n    return dict(form=form)\n\n@auth.requires_membership("Especialista")\ndef asignar_diagnostico():\n    response.flash = T("Asignar Diagn\xc3\xb3stico")\n    response.title = T("Asignar Diagn\xc3\xb3stico") + response.title\n    return dict()\n\nresponse._vars=response._caller(nuevo_diagnostico)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/opt/python/web2py-files/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/opt/python/web2py-files/web2py/applications/proyect/controllers/especialista.py", line 34, in <module>\n  File "/opt/python/web2py-files/web2py/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/opt/python/web2py-files/web2py/gluon/tools.py", line 4241, in f\n    return action(*a, **b)\n  File "/opt/python/web2py-files/web2py/applications/proyect/controllers/especialista.py", line 18, in nuevo_diagnostico\n    form.vars.id = db.auth_user.insert(**dict(form.vars))\n  File "/opt/python/web2py-files/web2py/gluon/packages/dal/pydal/objects.py", line 726, in insert\n    ret = self._db._adapter.insert(self, self._listify(fields))\n  File "/opt/python/web2py-files/web2py/gluon/packages/dal/pydal/objects.py", line 641, in _listify\n    \'Field %s does not belong to the table\' % name)\nSyntaxError: Field nombre does not belong to the table\n'
p11
s.