(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/opt/python/web2py-files/web2py/applications/proyect/views/estudiante/visor_preguntas.load'
p5
sS'code'
p6
S"response.write('<p>', escape=False)\nresponse.write(diagnostico.preguntas.select())\nresponse.write('</p>\\n', escape=False)"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/opt/python/web2py-files/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/opt/python/web2py-files/web2py/applications/proyect/views/estudiante/visor_preguntas.load", line 2, in <module>\n  File "/opt/python/web2py-files/web2py/gluon/packages/dal/pydal/objects.py", line 90, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.